{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "podinfo.serviceAccountName" . }}
{{- if .Values.customAnnotations }}
  annotations:
{{ toYaml .Values.customAnnotations | indent 4 }}
{{- end }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
{{- end -}}
